
/* This file was generated by idltool 53.35. Do not edit */


/***************************************************************************/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif

#ifdef __NOGLOBALIFACE__
#undef __NOGLOBALIFACE__
#endif

#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif

#ifndef PROTO_AMISSLEXT_H
#include <proto/amissl.h>
#endif

#ifndef EXEC_EMULATION_H
#include <exec/emulation.h>
#endif

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifndef DOS_DOS_H
#include <dos/dos.h>
#endif

#ifndef AMISSL_AMISSL_H
#include <amissl/amissl.h>
#endif

/***************************************************************************/

#if 0
STATIC struct Library * stub_ext_Open_PPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *)regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *)((uint32)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_ext_Open = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ext_Open_PPC };

// ---

STATIC APTR stub_ext_Close_PPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *)regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *)((uint32)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return Self->Close();
}
STATIC CONST struct EmuTrap stub_ext_Close = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ext_Close_PPC };

// ---

STATIC APTR stub_ext_Expunge_PPC(uint32 *regarray UNUSED)
{
	return NULL;
}
STATIC CONST struct EmuTrap stub_ext_Expunge = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ext_Expunge_PPC };

// ---

STATIC uint32 stub_ext_Reserved_PPC(uint32 *regarray UNUSED)
{
	return 0;
}
STATIC CONST struct EmuTrap stub_ext_Reserved = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ext_Reserved_PPC };
#endif

// ---

STATIC uint32 stub_ext_UNIMPLEMENTED_PPC(uint32 *regarray UNUSED)
{
	return 0;
}
STATIC CONST struct EmuTrap stub_ext_UNIMPLEMENTED = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_ext_UNIMPLEMENTED_PPC };

// ---

CONST CONST_APTR ext_VecTable68K[] =
{
	NULL,
	NULL,
	NULL,
	NULL,
	&stub_ext_UNIMPLEMENTED, /* PLACEHOLDER */
	(CONST_APTR)-1
};

/***************************************************************************/

