
/* This file was generated by idltool 53.35. Do not edit */


/***************************************************************************/

#ifndef GLUE_AMISSLEXT_H
#define GLUE_AMISSLEXT_H 1

#define PROTO_AMISSLEXT_H // Don't include protos
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#
#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifndef DOS_DOS_H
#include <dos/dos.h>
#endif

#ifndef AMISSL_AMISSL_H
#include <amissl/amissl.h>
#endif

#if defined(__amigaos4__)
struct AmiSSLIFace;
#define __IFACE_OR_BASE struct AmiSSLIFace *Self
#else
#define __IFACE_OR_BASE struct Library *Self
#endif

int SAVEDS ASM LIB_UNIMPLEMENTED(REG(a6, __IFACE_OR_BASE));

#if defined(SDI_LIB_H)
  #define SDI_LIBVECTOR_EXT \
    LFUNC_FAS(UNIMPLEMENTED) /* PLACEHOLDER */
#endif /* SDI_LIB_H */

#endif /* GLUE_AMISSLEXT_H */
