/*
** This file was automatically generated by fdtrans 51.4.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/amisslmaster.h>
#include <proto/amisslmaster.h>



STATIC ULONG stub_OpenPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Open(0);
}
const struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, stub_OpenPPC };

STATIC ULONG stub_ClosePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Close();
}
const struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, stub_ClosePPC };

STATIC ULONG stub_ExpungePPC(ULONG *regarray)
{
	return 0UL;
}
const struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray)
{
	return 0UL;
}
const struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static LONG stub_InitAmiSSLMasterPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct AmiSSLMasterIFace *Self = (struct AmiSSLMasterIFace *) ExtLib->MainIFace;

	return Self->InitAmiSSLMaster(
		(LONG)regarray[0],
		(LONG)regarray[1]
	);
}
const struct EmuTrap stub_InitAmiSSLMaster = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_InitAmiSSLMasterPPC };

static struct Library * stub_OpenAmiSSLPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct AmiSSLMasterIFace *Self = (struct AmiSSLMasterIFace *) ExtLib->MainIFace;

	return Self->OpenAmiSSL(
	);
}
const struct EmuTrap stub_OpenAmiSSL = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenAmiSSLPPC };

static void stub_CloseAmiSSLPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct AmiSSLMasterIFace *Self = (struct AmiSSLMasterIFace *) ExtLib->MainIFace;

	Self->CloseAmiSSL(
	);
}
const struct EmuTrap stub_CloseAmiSSL = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CloseAmiSSLPPC };

static struct Library * stub_OpenAmiSSLCipherPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct AmiSSLMasterIFace *Self = (struct AmiSSLMasterIFace *) ExtLib->MainIFace;

	return Self->OpenAmiSSLCipher(
		(LONG)regarray[0]
	);
}
const struct EmuTrap stub_OpenAmiSSLCipher = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenAmiSSLCipherPPC };

static void stub_CloseAmiSSLCipherPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct AmiSSLMasterIFace *Self = (struct AmiSSLMasterIFace *) ExtLib->MainIFace;

	Self->CloseAmiSSLCipher(
		(struct Library *)regarray[8]
	);
}
const struct EmuTrap stub_CloseAmiSSLCipher = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CloseAmiSSLCipherPPC };

const ULONG VecTable68K[] = {
	(ULONG)&stub_Open,
	(ULONG)&stub_Close,
	(ULONG)&stub_Expunge,
	(ULONG)&stub_Reserved,
	(ULONG)&stub_InitAmiSSLMaster,
	(ULONG)&stub_OpenAmiSSL,
	(ULONG)&stub_CloseAmiSSL,
	(ULONG)&stub_OpenAmiSSLCipher,
	(ULONG)&stub_CloseAmiSSLCipher,
	(ULONG)-1
};
