
/* This file was generated by idltool 53.13. Do not edit */

#include "amisslmaster_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    LIB_Obtain,
    LIB_Release,
    NULL,
    NULL,
    LIB_InitAmiSSLMaster,
    LIB_OpenAmiSSL,
    LIB_CloseAmiSSL,
    LIB_OpenAmiSSLCipher,
    LIB_CloseAmiSSLCipher,
    (APTR)-1
};

