
/* This file was generated by idltool 53.9. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

extern uint32               VARARGS68K LIB_Obtain(struct AmiSSLMasterIFace *);
extern uint32               VARARGS68K LIB_Release(struct AmiSSLMasterIFace *);
extern LONG                 VARARGS68K LIB_InitAmiSSLMaster(struct AmiSSLMasterIFace *, LONG APIVersion, LONG UsesOpenSSLStructs);
extern struct Library *     VARARGS68K LIB_OpenAmiSSL(struct AmiSSLMasterIFace *);
extern void                 VARARGS68K LIB_CloseAmiSSL(struct AmiSSLMasterIFace *);
extern struct Library *     VARARGS68K LIB_OpenAmiSSLCipher(struct AmiSSLMasterIFace *, LONG Cipher);
extern void                 VARARGS68K LIB_CloseAmiSSLCipher(struct AmiSSLMasterIFace *, struct Library * CipherBase);
