
/* This file was generated by idltool 53.6. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


extern ULONG                VARARGS68K _AmiSSLMaster_Obtain(struct AmiSSLMasterIFace *);
extern ULONG                VARARGS68K _AmiSSLMaster_Release(struct AmiSSLMasterIFace *);
extern LONG                 VARARGS68K _AmiSSLMaster_InitAmiSSLMaster(struct AmiSSLMasterIFace *, LONG APIVersion, LONG UsesOpenSSLStructs);
extern struct Library *     VARARGS68K _AmiSSLMaster_OpenAmiSSL(struct AmiSSLMasterIFace *);
extern void                 VARARGS68K _AmiSSLMaster_CloseAmiSSL(struct AmiSSLMasterIFace *);
extern struct Library *     VARARGS68K _AmiSSLMaster_OpenAmiSSLCipher(struct AmiSSLMasterIFace *, LONG Cipher);
extern void                 VARARGS68K _AmiSSLMaster_CloseAmiSSLCipher(struct AmiSSLMasterIFace *, struct Library * CipherBase);
